# Generated by Django 4.0.3 on 2022-05-02 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0005_alter_trainingtimer_finished_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 16, 2, 33, 585479, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
