# Generated by Django 4.0.3 on 2022-05-02 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0006_alter_trainingtimer_finished_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 14, 5, 8, 919828, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 16, 20, 8, 920825, tzinfo=utc)),
        ),
    ]
