# Generated by Django 4.0.3 on 2022-05-02 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0007_gorilla_feeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorilla',
            name='look',
            field=models.ImageField(default='images/gorilla16.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 17, 39, 28, 942507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 19, 54, 28, 943500, tzinfo=utc)),
        ),
    ]
