# Generated by Django 4.0.3 on 2022-05-02 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0010_alter_gorilla_feeding_alter_gorilla_look_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 17, 48, 1, 418322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gorilla',
            name='look',
            field=models.ImageField(default='gorilla16.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 20, 3, 1, 418322, tzinfo=utc)),
        ),
    ]
