# Generated by Django 4.0.3 on 2022-05-02 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0011_alter_gorilla_feeding_alter_gorilla_look_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 17, 53, 33, 124695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gorilla',
            name='look',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 20, 8, 33, 125693, tzinfo=utc)),
        ),
    ]
