# Generated by Django 4.0.3 on 2022-05-04 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0014_alter_gorilla_feeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 16, 36, 0, 209030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='information',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 18, 51, 0, 209030, tzinfo=utc)),
        ),
    ]
