# Generated by Django 4.0.3 on 2022-05-04 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0015_alter_gorilla_feeding_alter_profile_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 17, 23, 27, 492251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 19, 38, 27, 493249, tzinfo=utc)),
        ),
    ]
