# Generated by Django 4.0.3 on 2022-05-05 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0016_alter_gorilla_feeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='golden_banana',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 15, 30, 38, 38070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 17, 45, 38, 38070, tzinfo=utc)),
        ),
    ]
