# Generated by Django 4.0.3 on 2022-05-08 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0018_alter_gorilla_feeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 10, 32, 31, 759720, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 7, 10, 32, 31, 757725, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 12, 47, 31, 758722, tzinfo=utc)),
        ),
    ]
