# Generated by Django 4.0.3 on 2022-05-08 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monkeapp', '0019_letter_date_alter_gorilla_feeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opponent',
            name='look',
            field=models.ImageField(default='static/lion1', upload_to=''),
        ),
        migrations.AlterField(
            model_name='gorilla',
            name='feeding',
            field=models.DateField(default=datetime.datetime(2022, 5, 7, 10, 39, 48, 530568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 10, 39, 48, 531566, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='opponent',
            name='name',
            field=models.CharField(default='xyz', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingtimer',
            name='finished_training',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 12, 54, 48, 531566, tzinfo=utc)),
        ),
    ]
